// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/publisher/event_publisher.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/publisher/event_publisher.go -destination=mock_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	events "ecommerce-platform/proto-go/events"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishFromOutbox mocks base method.
func (m *MockEventPublisher) PublishFromOutbox(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFromOutbox", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFromOutbox indicates an expected call of PublishFromOutbox.
func (mr *MockEventPublisherMockRecorder) PublishFromOutbox(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFromOutbox", reflect.TypeOf((*MockEventPublisher)(nil).PublishFromOutbox), ctx, event)
}

// PublishStockCommitted mocks base method.
func (m *MockEventPublisher) PublishStockCommitted(ctx context.Context, event *events.StockCommitted) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStockCommitted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStockCommitted indicates an expected call of PublishStockCommitted.
func (mr *MockEventPublisherMockRecorder) PublishStockCommitted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStockCommitted", reflect.TypeOf((*MockEventPublisher)(nil).PublishStockCommitted), ctx, event)
}

// PublishStockReleased mocks base method.
func (m *MockEventPublisher) PublishStockReleased(ctx context.Context, event *events.StockReleased) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStockReleased", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStockReleased indicates an expected call of PublishStockReleased.
func (mr *MockEventPublisherMockRecorder) PublishStockReleased(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStockReleased", reflect.TypeOf((*MockEventPublisher)(nil).PublishStockReleased), ctx, event)
}

// PublishStockReserved mocks base method.
func (m *MockEventPublisher) PublishStockReserved(ctx context.Context, event *events.StockReserved) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStockReserved", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStockReserved indicates an expected call of PublishStockReserved.
func (mr *MockEventPublisherMockRecorder) PublishStockReserved(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStockReserved", reflect.TypeOf((*MockEventPublisher)(nil).PublishStockReserved), ctx, event)
}
