// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/repository/inventory_repository_facade.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/repository/inventory_repository_facade.go -destination=mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	aggregates "ecommerce-platform/services/inventory-service/internal/domain/aggregates"
	entities "ecommerce-platform/services/inventory-service/internal/domain/entities"
	repository "ecommerce-platform/services/inventory-service/internal/domain/ports/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInventoryRepositoryFacade is a mock of InventoryRepositoryFacade interface.
type MockInventoryRepositoryFacade struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryFacadeMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryFacadeMockRecorder is the mock recorder for MockInventoryRepositoryFacade.
type MockInventoryRepositoryFacadeMockRecorder struct {
	mock *MockInventoryRepositoryFacade
}

// NewMockInventoryRepositoryFacade creates a new mock instance.
func NewMockInventoryRepositoryFacade(ctrl *gomock.Controller) *MockInventoryRepositoryFacade {
	mock := &MockInventoryRepositoryFacade{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepositoryFacade) EXPECT() *MockInventoryRepositoryFacadeMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockInventoryRepositoryFacade) CreateProduct(ctx context.Context, product *entities.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockInventoryRepositoryFacadeMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).CreateProduct), ctx, product)
}

// DeleteProduct mocks base method.
func (m *MockInventoryRepositoryFacade) DeleteProduct(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockInventoryRepositoryFacadeMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).DeleteProduct), ctx, id)
}

// GetProductByID mocks base method.
func (m *MockInventoryRepositoryFacade) GetProductByID(ctx context.Context, id string) (*entities.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*entities.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockInventoryRepositoryFacadeMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).GetProductByID), ctx, id)
}

// GetStockByID mocks base method.
func (m *MockInventoryRepositoryFacade) GetStockByID(ctx context.Context, id string) (*entities.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByID", ctx, id)
	ret0, _ := ret[0].(*entities.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByID indicates an expected call of GetStockByID.
func (mr *MockInventoryRepositoryFacadeMockRecorder) GetStockByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByID", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).GetStockByID), ctx, id)
}

// GetStockByProductID mocks base method.
func (m *MockInventoryRepositoryFacade) GetStockByProductID(ctx context.Context, productID string) (*entities.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByProductID", ctx, productID)
	ret0, _ := ret[0].(*entities.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByProductID indicates an expected call of GetStockByProductID.
func (mr *MockInventoryRepositoryFacadeMockRecorder) GetStockByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByProductID", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).GetStockByProductID), ctx, productID)
}

// GetStocksByProductIDs mocks base method.
func (m *MockInventoryRepositoryFacade) GetStocksByProductIDs(ctx context.Context, productIDs []string, forUpdate bool) (map[string]*entities.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocksByProductIDs", ctx, productIDs, forUpdate)
	ret0, _ := ret[0].(map[string]*entities.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocksByProductIDs indicates an expected call of GetStocksByProductIDs.
func (mr *MockInventoryRepositoryFacadeMockRecorder) GetStocksByProductIDs(ctx, productIDs, forUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocksByProductIDs", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).GetStocksByProductIDs), ctx, productIDs, forUpdate)
}

// GetUnprocessedEvents mocks base method.
func (m *MockInventoryRepositoryFacade) GetUnprocessedEvents(ctx context.Context, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedEvents", ctx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedEvents indicates an expected call of GetUnprocessedEvents.
func (mr *MockInventoryRepositoryFacadeMockRecorder) GetUnprocessedEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedEvents", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).GetUnprocessedEvents), ctx, limit)
}

// ListProducts mocks base method.
func (m *MockInventoryRepositoryFacade) ListProducts(ctx context.Context, page, limit int, search string) ([]*entities.Product, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, page, limit, search)
	ret0, _ := ret[0].([]*entities.Product)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockInventoryRepositoryFacadeMockRecorder) ListProducts(ctx, page, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).ListProducts), ctx, page, limit, search)
}

// ListProductsWithStock mocks base method.
func (m *MockInventoryRepositoryFacade) ListProductsWithStock(ctx context.Context, page, limit int, search string) ([]*aggregates.ProductInventory, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsWithStock", ctx, page, limit, search)
	ret0, _ := ret[0].([]*aggregates.ProductInventory)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProductsWithStock indicates an expected call of ListProductsWithStock.
func (mr *MockInventoryRepositoryFacadeMockRecorder) ListProductsWithStock(ctx, page, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsWithStock", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).ListProductsWithStock), ctx, page, limit, search)
}

// MarkAsFailed mocks base method.
func (m *MockInventoryRepositoryFacade) MarkAsFailed(ctx context.Context, id uint, err string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", ctx, id, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockInventoryRepositoryFacadeMockRecorder) MarkAsFailed(ctx, id, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).MarkAsFailed), ctx, id, err)
}

// MarkAsProcessed mocks base method.
func (m *MockInventoryRepositoryFacade) MarkAsProcessed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessed indicates an expected call of MarkAsProcessed.
func (mr *MockInventoryRepositoryFacadeMockRecorder) MarkAsProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessed", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).MarkAsProcessed), ctx, id)
}

// ProductExistsByID mocks base method.
func (m *MockInventoryRepositoryFacade) ProductExistsByID(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductExistsByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProductExistsByID indicates an expected call of ProductExistsByID.
func (mr *MockInventoryRepositoryFacadeMockRecorder) ProductExistsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductExistsByID", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).ProductExistsByID), ctx, id)
}

// SaveEvent mocks base method.
func (m *MockInventoryRepositoryFacade) SaveEvent(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockInventoryRepositoryFacadeMockRecorder) SaveEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).SaveEvent), ctx, event)
}

// StockExistsByID mocks base method.
func (m *MockInventoryRepositoryFacade) StockExistsByID(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StockExistsByID", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StockExistsByID indicates an expected call of StockExistsByID.
func (mr *MockInventoryRepositoryFacadeMockRecorder) StockExistsByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StockExistsByID", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).StockExistsByID), ctx, id)
}

// UpdateProduct mocks base method.
func (m *MockInventoryRepositoryFacade) UpdateProduct(ctx context.Context, product *entities.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockInventoryRepositoryFacadeMockRecorder) UpdateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).UpdateProduct), ctx, product)
}

// UpsertStock mocks base method.
func (m *MockInventoryRepositoryFacade) UpsertStock(ctx context.Context, stock *entities.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStock", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStock indicates an expected call of UpsertStock.
func (mr *MockInventoryRepositoryFacadeMockRecorder) UpsertStock(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStock", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).UpsertStock), ctx, stock)
}

// UpsertStocks mocks base method.
func (m *MockInventoryRepositoryFacade) UpsertStocks(ctx context.Context, stocks []*entities.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStocks", ctx, stocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertStocks indicates an expected call of UpsertStocks.
func (mr *MockInventoryRepositoryFacadeMockRecorder) UpsertStocks(ctx, stocks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStocks", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).UpsertStocks), ctx, stocks)
}

// WithTransaction mocks base method.
func (m *MockInventoryRepositoryFacade) WithTransaction(ctx context.Context, fn func(repository.InventoryRepositoryFacade) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockInventoryRepositoryFacadeMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockInventoryRepositoryFacade)(nil).WithTransaction), ctx, fn)
}
