// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/repository/order_repository_facade.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/repository/order_repository_facade.go -destination=mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	aggregates "ecommerce-platform/services/order-service/internal/domain/aggregates"
	repository "ecommerce-platform/services/order-service/internal/domain/ports/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepositoryFacade is a mock of OrderRepositoryFacade interface.
type MockOrderRepositoryFacade struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryFacadeMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryFacadeMockRecorder is the mock recorder for MockOrderRepositoryFacade.
type MockOrderRepositoryFacadeMockRecorder struct {
	mock *MockOrderRepositoryFacade
}

// NewMockOrderRepositoryFacade creates a new mock instance.
func NewMockOrderRepositoryFacade(ctrl *gomock.Controller) *MockOrderRepositoryFacade {
	mock := &MockOrderRepositoryFacade{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepositoryFacade) EXPECT() *MockOrderRepositoryFacadeMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepositoryFacade) Create(ctx context.Context, order *aggregates.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryFacadeMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).Create), ctx, order)
}

// GetByID mocks base method.
func (m *MockOrderRepositoryFacade) GetByID(ctx context.Context, id string) (*aggregates.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*aggregates.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderRepositoryFacadeMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockOrderRepositoryFacade) GetByUserID(ctx context.Context, userID string, page, limit int) ([]*aggregates.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, page, limit)
	ret0, _ := ret[0].([]*aggregates.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOrderRepositoryFacadeMockRecorder) GetByUserID(ctx, userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).GetByUserID), ctx, userID, page, limit)
}

// GetUnprocessedEvents mocks base method.
func (m *MockOrderRepositoryFacade) GetUnprocessedEvents(ctx context.Context, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedEvents", ctx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedEvents indicates an expected call of GetUnprocessedEvents.
func (mr *MockOrderRepositoryFacadeMockRecorder) GetUnprocessedEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedEvents", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).GetUnprocessedEvents), ctx, limit)
}

// MarkAsFailed mocks base method.
func (m *MockOrderRepositoryFacade) MarkAsFailed(ctx context.Context, id uint, err string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", ctx, id, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockOrderRepositoryFacadeMockRecorder) MarkAsFailed(ctx, id, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).MarkAsFailed), ctx, id, err)
}

// MarkAsProcessed mocks base method.
func (m *MockOrderRepositoryFacade) MarkAsProcessed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessed indicates an expected call of MarkAsProcessed.
func (mr *MockOrderRepositoryFacadeMockRecorder) MarkAsProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessed", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).MarkAsProcessed), ctx, id)
}

// SaveEvent mocks base method.
func (m *MockOrderRepositoryFacade) SaveEvent(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockOrderRepositoryFacadeMockRecorder) SaveEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).SaveEvent), ctx, event)
}

// Update mocks base method.
func (m *MockOrderRepositoryFacade) Update(ctx context.Context, order *aggregates.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrderRepositoryFacadeMockRecorder) Update(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).Update), ctx, order)
}

// WithTransaction mocks base method.
func (m *MockOrderRepositoryFacade) WithTransaction(ctx context.Context, fn func(repository.OrderRepositoryFacade) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockOrderRepositoryFacadeMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockOrderRepositoryFacade)(nil).WithTransaction), ctx, fn)
}
