// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/publisher/order_created_publisher.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/publisher/order_created_publisher.go -destination=mock_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	events "ecommerce-platform/proto-go/events"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// PublishFromOutbox mocks base method.
func (m *MockEventPublisher) PublishFromOutbox(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFromOutbox", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFromOutbox indicates an expected call of PublishFromOutbox.
func (mr *MockEventPublisherMockRecorder) PublishFromOutbox(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFromOutbox", reflect.TypeOf((*MockEventPublisher)(nil).PublishFromOutbox), ctx, event)
}

// PublishOrderCancelled mocks base method.
func (m *MockEventPublisher) PublishOrderCancelled(ctx context.Context, event *events.OrderCancelled) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCancelled", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCancelled indicates an expected call of PublishOrderCancelled.
func (mr *MockEventPublisherMockRecorder) PublishOrderCancelled(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCancelled", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderCancelled), ctx, event)
}

// PublishOrderCreated mocks base method.
func (m *MockEventPublisher) PublishOrderCreated(ctx context.Context, event *events.OrderCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCreated indicates an expected call of PublishOrderCreated.
func (mr *MockEventPublisherMockRecorder) PublishOrderCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishOrderCreated), ctx, event)
}
