package usecases

import (
	"context"
	"fmt"
	"time"

	"ecommerce-platform/pkg/common/errors"
	"ecommerce-platform/pkg/logger"
	"ecommerce-platform/services/inventory-service/internal/application/dto"
	"ecommerce-platform/services/inventory-service/internal/domain/entities"
	"ecommerce-platform/services/inventory-service/internal/domain/ports/repository"
)

// CreateProductUseCase handles product creation
type CreateProductUseCase struct {
	inventoryRepo repository.InventoryRepository
	logger        logger.Logger
}

// NewCreateProductUseCase creates a new create product use case
func NewCreateProductUseCase(inventoryRepo repository.InventoryRepository, logger logger.Logger) *CreateProductUseCase {
	return &CreateProductUseCase{
		inventoryRepo: inventoryRepo,
		logger:        logger,
	}
}

// Execute creates a new product
func (uc *CreateProductUseCase) Execute(ctx context.Context, req *dto.CreateProductRequest) (*dto.ProductResponse, error) {
	// Validate request
	if err := uc.validateRequest(req); err != nil {
		return nil, fmt.Errorf("failed to validate request: %w", err)
	}

	// Generate product ID (in real app, this would be generated by ID service)
	productID := fmt.Sprintf("product_%d", time.Now().UnixNano())

	// Check if product already exists
	existingProduct, err := uc.inventoryRepo.GetProductByID(ctx, productID)
	if err == nil && existingProduct != nil {
		return nil, errors.ErrProductAlreadyExists
	}

	// Create product entity
	product := entities.NewProduct(
		productID,
		req.Name,
		req.Price,
		req.ImageURL,
	)

	// Validate product
	if err := product.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate product: %w", err)
	}

	// Use transaction to ensure both product and stock are created atomically
	var stock *entities.Stock
	err = uc.inventoryRepo.WithTransaction(ctx, func(repo repository.InventoryRepository) error {
		// Save product
		if err := repo.CreateProduct(ctx, product); err != nil {
			return fmt.Errorf("failed to create product: %w", err)
		}

		// Create stock for the product
		stock = entities.NewStock(productID, req.Stock, 0)
		if err := repo.CreateStock(ctx, stock); err != nil {
			return fmt.Errorf("failed to create stock for product: %w", err)
		}

		return nil
	})

	if err != nil {
		uc.logger.Error("failed to create product and stock", "productID", productID, "error", err)
		return nil, err
	}

	uc.logger.Info("product created successfully", "productID", product.ID, "name", product.Name)

	// Convert to response
	response := &dto.ProductResponse{
		ID:       product.ID,
		Name:     product.Name,
		Price:    product.Price,
		ImageURL: product.ImageURL,
		Stock: dto.StockInfo{
			AvailableQuantity: stock.AvailableQuantity,
			ReservedQuantity:  stock.ReservedQuantity,
			TotalQuantity:     stock.AvailableQuantity + stock.ReservedQuantity,
		},
		CreatedAt: product.CreatedAt,
		UpdatedAt: product.UpdatedAt,
	}

	return response, nil
}

// validateRequest validates the create product request
func (uc *CreateProductUseCase) validateRequest(req *dto.CreateProductRequest) error {
	if req == nil {
		return errors.ErrInvalidRequest
	}
	if req.Name == "" {
		return errors.ErrInvalidProductName
	}
	if req.Price.IsZero() {
		return errors.ErrInvalidProductPrice
	}
	if req.Stock < 0 {
		return errors.ErrInvalidQuantity
	}
	return nil
}
