// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/metrics/payment_metrics.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/metrics/payment_metrics.go -destination=mock_payment_metrics.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentMetrics is a mock of PaymentMetrics interface.
type MockPaymentMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMetricsMockRecorder
	isgomock struct{}
}

// MockPaymentMetricsMockRecorder is the mock recorder for MockPaymentMetrics.
type MockPaymentMetricsMockRecorder struct {
	mock *MockPaymentMetrics
}

// NewMockPaymentMetrics creates a new mock instance.
func NewMockPaymentMetrics(ctrl *gomock.Controller) *MockPaymentMetrics {
	mock := &MockPaymentMetrics{ctrl: ctrl}
	mock.recorder = &MockPaymentMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMetrics) EXPECT() *MockPaymentMetricsMockRecorder {
	return m.recorder
}

// EntityEvent mocks base method.
func (m *MockPaymentMetrics) EntityEvent(entityType, action, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EntityEvent", entityType, action, reason)
}

// EntityEvent indicates an expected call of EntityEvent.
func (mr *MockPaymentMetricsMockRecorder) EntityEvent(entityType, action, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntityEvent", reflect.TypeOf((*MockPaymentMetrics)(nil).EntityEvent), entityType, action, reason)
}

// GRPCRequestDuration mocks base method.
func (m *MockPaymentMetrics) GRPCRequestDuration(method string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GRPCRequestDuration", method, duration)
}

// GRPCRequestDuration indicates an expected call of GRPCRequestDuration.
func (mr *MockPaymentMetricsMockRecorder) GRPCRequestDuration(method, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GRPCRequestDuration", reflect.TypeOf((*MockPaymentMetrics)(nil).GRPCRequestDuration), method, duration)
}

// GRPCRequestTotal mocks base method.
func (m *MockPaymentMetrics) GRPCRequestTotal(method, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GRPCRequestTotal", method, status)
}

// GRPCRequestTotal indicates an expected call of GRPCRequestTotal.
func (mr *MockPaymentMetricsMockRecorder) GRPCRequestTotal(method, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GRPCRequestTotal", reflect.TypeOf((*MockPaymentMetrics)(nil).GRPCRequestTotal), method, status)
}

// HTTPRequestDuration mocks base method.
func (m *MockPaymentMetrics) HTTPRequestDuration(method, endpoint string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HTTPRequestDuration", method, endpoint, duration)
}

// HTTPRequestDuration indicates an expected call of HTTPRequestDuration.
func (mr *MockPaymentMetricsMockRecorder) HTTPRequestDuration(method, endpoint, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPRequestDuration", reflect.TypeOf((*MockPaymentMetrics)(nil).HTTPRequestDuration), method, endpoint, duration)
}

// HTTPRequestsTotal mocks base method.
func (m *MockPaymentMetrics) HTTPRequestsTotal(method, endpoint, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HTTPRequestsTotal", method, endpoint, status)
}

// HTTPRequestsTotal indicates an expected call of HTTPRequestsTotal.
func (mr *MockPaymentMetricsMockRecorder) HTTPRequestsTotal(method, endpoint, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPRequestsTotal", reflect.TypeOf((*MockPaymentMetrics)(nil).HTTPRequestsTotal), method, endpoint, status)
}
