// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/repository/outbox_repository.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/repository/outbox_repository.go -destination=mock_outbox_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// GetUnprocessedEvents mocks base method.
func (m *MockOutboxRepository) GetUnprocessedEvents(ctx context.Context, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedEvents", ctx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedEvents indicates an expected call of GetUnprocessedEvents.
func (mr *MockOutboxRepositoryMockRecorder) GetUnprocessedEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedEvents", reflect.TypeOf((*MockOutboxRepository)(nil).GetUnprocessedEvents), ctx, limit)
}

// MarkAsFailed mocks base method.
func (m *MockOutboxRepository) MarkAsFailed(ctx context.Context, id uint, err string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", ctx, id, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsFailed(ctx, id, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsFailed), ctx, id, err)
}

// MarkAsProcessed mocks base method.
func (m *MockOutboxRepository) MarkAsProcessed(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessed indicates an expected call of MarkAsProcessed.
func (mr *MockOutboxRepositoryMockRecorder) MarkAsProcessed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkAsProcessed), ctx, id)
}

// SaveEvent mocks base method.
func (m *MockOutboxRepository) SaveEvent(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockOutboxRepositoryMockRecorder) SaveEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockOutboxRepository)(nil).SaveEvent), ctx, event)
}
