// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/publisher/payment_events_publisher.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/publisher/payment_events_publisher.go -destination=mock_payment_events_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	outbox "ecommerce-platform/pkg/outbox"
	events "ecommerce-platform/proto-go/events"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentEventsPublisher is a mock of PaymentEventsPublisher interface.
type MockPaymentEventsPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentEventsPublisherMockRecorder
	isgomock struct{}
}

// MockPaymentEventsPublisherMockRecorder is the mock recorder for MockPaymentEventsPublisher.
type MockPaymentEventsPublisherMockRecorder struct {
	mock *MockPaymentEventsPublisher
}

// NewMockPaymentEventsPublisher creates a new mock instance.
func NewMockPaymentEventsPublisher(ctrl *gomock.Controller) *MockPaymentEventsPublisher {
	mock := &MockPaymentEventsPublisher{ctrl: ctrl}
	mock.recorder = &MockPaymentEventsPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentEventsPublisher) EXPECT() *MockPaymentEventsPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPaymentEventsPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPaymentEventsPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPaymentEventsPublisher)(nil).Close))
}

// PublishFromOutbox mocks base method.
func (m *MockPaymentEventsPublisher) PublishFromOutbox(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFromOutbox", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFromOutbox indicates an expected call of PublishFromOutbox.
func (mr *MockPaymentEventsPublisherMockRecorder) PublishFromOutbox(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFromOutbox", reflect.TypeOf((*MockPaymentEventsPublisher)(nil).PublishFromOutbox), ctx, event)
}

// PublishPaymentProcessed mocks base method.
func (m *MockPaymentEventsPublisher) PublishPaymentProcessed(ctx context.Context, event *events.PaymentProcessed) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentProcessed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentProcessed indicates an expected call of PublishPaymentProcessed.
func (mr *MockPaymentEventsPublisherMockRecorder) PublishPaymentProcessed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentProcessed", reflect.TypeOf((*MockPaymentEventsPublisher)(nil).PublishPaymentProcessed), ctx, event)
}
