package grpc

import (
	"context"
	"time"

	"ecommerce-platform/pkg/common/grpcutils"
	"ecommerce-platform/pkg/common/valueobjects"
	"ecommerce-platform/proto-go/common"
	pb "ecommerce-platform/proto-go/payment"
	"ecommerce-platform/services/payment-service/internal/application/dto"
	appsvc "ecommerce-platform/services/payment-service/internal/application/services"
	paymentvalueobjects "ecommerce-platform/services/payment-service/internal/domain/valueobjects"
	"ecommerce-platform/services/payment-service/internal/metrics"

	"google.golang.org/protobuf/types/known/timestamppb"
)

type PBPaymentServer struct {
	pb.UnimplementedPaymentServiceServer
	svc     *appsvc.PaymentApplicationService
	metrics metrics.PaymentMetrics
}

func NewPBPaymentServer(svc *appsvc.PaymentApplicationService, metrics metrics.PaymentMetrics) *PBPaymentServer {
	return &PBPaymentServer{
		svc:     svc,
		metrics: metrics,
	}
}

// helpers
func toPBStatus(s paymentvalueobjects.PaymentStatus) pb.PaymentStatus {
	switch s {
	case paymentvalueobjects.PaymentStatusCompleted:
		return pb.PaymentStatus_PAYMENT_COMPLETED
	case paymentvalueobjects.PaymentStatusFailed:
		fallthrough
	default:
		return pb.PaymentStatus_PAYMENT_FAILED
	}
}

func toPBMethod(m paymentvalueobjects.PaymentMethod) pb.PaymentMethod {
	switch m {
	case paymentvalueobjects.PaymentMethodCreditCard:
		return pb.PaymentMethod_CREDIT_CARD
	default:
		return pb.PaymentMethod_CREDIT_CARD
	}
}

func toPBPayment(p *dto.PaymentResponse) *pb.Payment {
	if p == nil {
		return nil
	}
	return &pb.Payment{
		Id:            p.ID,
		OrderId:       p.OrderID,
		UserId:        p.UserID,
		Amount:        &common.Money{Amount: p.Amount.Amount, Currency: p.Amount.Currency.String()},
		Status:        toPBStatus(paymentvalueobjects.PaymentStatus(p.Status)),
		Method:        toPBMethod(paymentvalueobjects.PaymentMethod(p.Method)),
		TransactionId: p.TransactionID,
		CreatedAt:     timestamppb.New(p.CreatedAt.UTC()),
		UpdatedAt:     timestamppb.New(p.UpdatedAt.UTC()),
	}
}

func (s *PBPaymentServer) ProcessPayment(ctx context.Context, req *pb.ProcessPaymentRequest) (*pb.ProcessPaymentResponse, error) {
	start := time.Now()
	methodName := "ProcessPayment"
	status := "success"
	defer func() {
		s.metrics.GRPCRequestDuration(methodName, time.Since(start))
		s.metrics.GRPCRequestTotal(methodName, status)
	}()

	currency, err := valueobjects.NewCurrency(req.Amount.Currency)
	if err != nil {
		status = "error"
		return nil, grpcutils.MapErrorToStatus(err)
	}

	amt := valueobjects.Money{
		Amount:   req.Amount.Amount,
		Currency: currency,
	}

	// Convert proto PaymentDetails to DTO PaymentDetails
	var paymentDetails *dto.PaymentDetails
	if req.Details != nil {
		paymentDetails = &dto.PaymentDetails{
			CardNumber:  req.Details.CardNumber,
			CardHolder:  req.Details.CardHolder,
			ExpiryMonth: req.Details.ExpiryMonth,
			ExpiryYear:  req.Details.ExpiryYear,
			CVV:         req.Details.Cvv,
		}
	}

	// Convert proto PaymentMethod to domain PaymentMethod
	var paymentMethod paymentvalueobjects.PaymentMethod
	switch req.Method {
	case pb.PaymentMethod_CREDIT_CARD:
		paymentMethod = paymentvalueobjects.PaymentMethodCreditCard
	default:
		paymentMethod = paymentvalueobjects.PaymentMethodCreditCard // Default fallback
	}

	// Process payment directly
	processReq := &dto.ProcessPaymentRequest{
		PaymentID: "", // Will be generated by ProcessPaymentUseCase
		OrderID:   req.OrderId,
		UserID:    req.UserId,
		Amount:    amt,
		Method:    paymentMethod,
		Details:   paymentDetails,
	}

	resp, err := s.svc.ProcessPayment(ctx, processReq)
	if err != nil {
		status = "error"
		return nil, grpcutils.MapErrorToStatus(err)
	}

	// Build response
	success := resp.Status == paymentvalueobjects.PaymentStatusCompleted

	message := "Payment processing failed"
	if success {
		message = "Payment processed successfully"
	}

	return &pb.ProcessPaymentResponse{
		Payment: toPBPayment(resp),
		Success: success,
		Message: message,
	}, nil
}
