package services

import (
	"context"
	"fmt"

	"ecommerce-platform/pkg/common/valueobjects"
	"ecommerce-platform/pkg/logger"
	"ecommerce-platform/proto-go/events"
	"ecommerce-platform/services/payment-service/internal/application/dto"
	"ecommerce-platform/services/payment-service/internal/application/usecases"
	paymentvalueobjects "ecommerce-platform/services/payment-service/internal/domain/valueobjects"
)

// StockEventService orchestrates stock event processing
type StockEventService struct {
	processPaymentUseCase *usecases.ProcessPaymentUseCase
	logger                logger.Logger
}

// NewStockEventService creates a new StockEventService instance
func NewStockEventService(processPaymentUseCase *usecases.ProcessPaymentUseCase, logger logger.Logger) *StockEventService {
	return &StockEventService{
		processPaymentUseCase: processPaymentUseCase,
		logger:                logger,
	}
}

// ProcessStockReserved processes StockReserved events and processes payments
func (s *StockEventService) ProcessStockReserved(ctx context.Context, evt *events.StockReserved) error {
	// Basic nil check only
	if evt == nil {
		return fmt.Errorf("event is nil")
	}

	// Convert event to DTO for payment processing
	currency, err := valueobjects.NewCurrency(evt.Currency)
	if err != nil {
		return err
	}

	// Convert proto PaymentDetails to DTO PaymentDetails
	var paymentDetails *dto.PaymentDetails
	if evt.PaymentDetails != nil {
		paymentDetails = &dto.PaymentDetails{
			CardNumber:  evt.PaymentDetails.CardNumber,
			CardHolder:  evt.PaymentDetails.CardHolder,
			ExpiryMonth: evt.PaymentDetails.ExpiryMonth,
			ExpiryYear:  evt.PaymentDetails.ExpiryYear,
			CVV:         evt.PaymentDetails.Cvv,
		}
	}

	req := dto.ProcessPaymentRequest{
		PaymentID: "", // Will be generated by ProcessPaymentUseCase
		OrderID:   evt.OrderId,
		UserID:    evt.UserId,
		Amount: valueobjects.Money{
			Amount:   evt.TotalAmount,
			Currency: currency,
		},
		Method:  paymentvalueobjects.PaymentMethodCreditCard, // Default method for stock events
		Details: paymentDetails,
	}

	// Process payment using application use case
	if _, err := s.processPaymentUseCase.Execute(ctx, req.OrderID, req.UserID, req.Amount, req.Method); err != nil {
		return err
	}

	return nil
}
