// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/domain/ports/services/token_generator.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/domain/ports/services/token_generator.go -destination=mock_token_generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	jwt "ecommerce-platform/pkg/jwt"
	valueobjects "ecommerce-platform/services/user-service/internal/domain/valueobjects"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// GenerateTokenPair mocks base method.
func (m *MockTokenGenerator) GenerateTokenPair(userID string) (valueobjects.Token, valueobjects.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", userID)
	ret0, _ := ret[0].(valueobjects.Token)
	ret1, _ := ret[1].(valueobjects.Token)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenGeneratorMockRecorder) GenerateTokenPair(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenGenerator)(nil).GenerateTokenPair), userID)
}

// ValidateToken mocks base method.
func (m *MockTokenGenerator) ValidateToken(token string) (*jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(*jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenGeneratorMockRecorder) ValidateToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenGenerator)(nil).ValidateToken), token)
}
