root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/main.go"
bin = "./tmp/app"
include_dir = [".", "../../proto-go"]
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test.go$"]
delay = 1000
stop_on_error = true
kill_delay = 500

[log]
time = true
color = true


