// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/clients/inventory_client.go
//
// Generated by this command:
//
//	mockgen -source=../../internal/clients/inventory_client.go -destination=mock_inventory_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	clients "ecommerce-platform/services/api-gateway/internal/clients"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInventoryClient is a mock of InventoryClient interface.
type MockInventoryClient struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryClientMockRecorder
	isgomock struct{}
}

// MockInventoryClientMockRecorder is the mock recorder for MockInventoryClient.
type MockInventoryClientMockRecorder struct {
	mock *MockInventoryClient
}

// NewMockInventoryClient creates a new mock instance.
func NewMockInventoryClient(ctrl *gomock.Controller) *MockInventoryClient {
	mock := &MockInventoryClient{ctrl: ctrl}
	mock.recorder = &MockInventoryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryClient) EXPECT() *MockInventoryClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInventoryClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockInventoryClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInventoryClient)(nil).Close))
}

// GetProduct mocks base method.
func (m *MockInventoryClient) GetProduct(ctx context.Context, id string) (*clients.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, id)
	ret0, _ := ret[0].(*clients.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockInventoryClientMockRecorder) GetProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockInventoryClient)(nil).GetProduct), ctx, id)
}

// GetProducts mocks base method.
func (m *MockInventoryClient) GetProducts(ctx context.Context, categoryID string, page, limit int, search string) (*clients.ListProductsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx, categoryID, page, limit, search)
	ret0, _ := ret[0].(*clients.ListProductsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockInventoryClientMockRecorder) GetProducts(ctx, categoryID, page, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockInventoryClient)(nil).GetProducts), ctx, categoryID, page, limit, search)
}
