// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: events/inventory_events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockReserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // RFC3339
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReserved) Reset() {
	*x = StockReserved{}
	mi := &file_events_inventory_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReserved) ProtoMessage() {}

func (x *StockReserved) ProtoReflect() protoreflect.Message {
	mi := &file_events_inventory_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReserved.ProtoReflect.Descriptor instead.
func (*StockReserved) Descriptor() ([]byte, []int) {
	return file_events_inventory_events_proto_rawDescGZIP(), []int{0}
}

func (x *StockReserved) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockReserved) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *StockReserved) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StockReservationFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // RFC3339
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReservationFailed) Reset() {
	*x = StockReservationFailed{}
	mi := &file_events_inventory_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReservationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReservationFailed) ProtoMessage() {}

func (x *StockReservationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_events_inventory_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReservationFailed.ProtoReflect.Descriptor instead.
func (*StockReservationFailed) Descriptor() ([]byte, []int) {
	return file_events_inventory_events_proto_rawDescGZIP(), []int{1}
}

func (x *StockReservationFailed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockReservationFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StockReservationFailed) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *StockReservationFailed) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_events_inventory_events_proto protoreflect.FileDescriptor

const file_events_inventory_events_proto_rawDesc = "" +
	"\n" +
	"\x1devents/inventory_events.proto\x12\x10events.inventory\"d\n" +
	"\rStockReserved\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\voccurred_at\x18\x02 \x01(\tR\n" +
	"occurredAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x85\x01\n" +
	"\x16StockReservationFailed\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\voccurred_at\x18\x03 \x01(\tR\n" +
	"occurredAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userIdB\x11Z\x0fproto-go/eventsb\x06proto3"

var (
	file_events_inventory_events_proto_rawDescOnce sync.Once
	file_events_inventory_events_proto_rawDescData []byte
)

func file_events_inventory_events_proto_rawDescGZIP() []byte {
	file_events_inventory_events_proto_rawDescOnce.Do(func() {
		file_events_inventory_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_inventory_events_proto_rawDesc), len(file_events_inventory_events_proto_rawDesc)))
	})
	return file_events_inventory_events_proto_rawDescData
}

var file_events_inventory_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_inventory_events_proto_goTypes = []any{
	(*StockReserved)(nil),          // 0: events.inventory.StockReserved
	(*StockReservationFailed)(nil), // 1: events.inventory.StockReservationFailed
}
var file_events_inventory_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_inventory_events_proto_init() }
func file_events_inventory_events_proto_init() {
	if File_events_inventory_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_inventory_events_proto_rawDesc), len(file_events_inventory_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_inventory_events_proto_goTypes,
		DependencyIndexes: file_events_inventory_events_proto_depIdxs,
		MessageInfos:      file_events_inventory_events_proto_msgTypes,
	}.Build()
	File_events_inventory_events_proto = out.File
	file_events_inventory_events_proto_goTypes = nil
	file_events_inventory_events_proto_depIdxs = nil
}
