// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: events/payment_events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentProcessed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                          // minor units
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`                       // ISO 4217
	OccurredAt    string                 `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentProcessed) Reset() {
	*x = PaymentProcessed{}
	mi := &file_events_payment_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProcessed) ProtoMessage() {}

func (x *PaymentProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_events_payment_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProcessed.ProtoReflect.Descriptor instead.
func (*PaymentProcessed) Descriptor() ([]byte, []int) {
	return file_events_payment_events_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentProcessed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentProcessed) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentProcessed) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentProcessed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentProcessed) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentProcessed) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentProcessed) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

var File_events_payment_events_proto protoreflect.FileDescriptor

const file_events_payment_events_proto_rawDesc = "" +
	"\n" +
	"\x1bevents/payment_events.proto\x12\x0eevents.payment\"\xd5\x01\n" +
	"\x10PaymentProcessed\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\tR\n" +
	"occurredAtB\x11Z\x0fproto-go/eventsb\x06proto3"

var (
	file_events_payment_events_proto_rawDescOnce sync.Once
	file_events_payment_events_proto_rawDescData []byte
)

func file_events_payment_events_proto_rawDescGZIP() []byte {
	file_events_payment_events_proto_rawDescOnce.Do(func() {
		file_events_payment_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_payment_events_proto_rawDesc), len(file_events_payment_events_proto_rawDesc)))
	})
	return file_events_payment_events_proto_rawDescData
}

var file_events_payment_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_payment_events_proto_goTypes = []any{
	(*PaymentProcessed)(nil), // 0: events.payment.PaymentProcessed
}
var file_events_payment_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_payment_events_proto_init() }
func file_events_payment_events_proto_init() {
	if File_events_payment_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_payment_events_proto_rawDesc), len(file_events_payment_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_payment_events_proto_goTypes,
		DependencyIndexes: file_events_payment_events_proto_depIdxs,
		MessageInfos:      file_events_payment_events_proto_msgTypes,
	}.Build()
	File_events_payment_events_proto = out.File
	file_events_payment_events_proto_goTypes = nil
	file_events_payment_events_proto_depIdxs = nil
}
